name: Rust Build & Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set outputs
        id: outputs
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> "$GITHUB_OUTPUT" &&
          echo "ARCH=${${{ matrix.platform }} | cut -d'/' -f2- }" >> "$GITHUB_OUTPUT"

      - name: Set up rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: 'true'
      - name: Build
        run: cargo build --release

      - name: Package
        run: tar -czvf release-${{ steps.variables.outputs.ARCH }}.tar.gz -C target/release .

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release-${{ steps.variables.outputs.ARCH }}.tar.gz
          name: Release for commit ${{ steps.shorten_sha.outputs.SHORT_SHA }}
          tag: ${{ steps.shorten_sha.outputs.SHORT_SHA }}
