name: Rust Build & Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set outputs
        id: outputs
        env:
          PLATFORM=${{ matrix.platform }}
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> "$GITHUB_OUTPUT" &&
          echo "ARCH=${$PLATFORM | cut -d'/' -f2- }" >> "$GITHUB_OUTPUT"

      - name: Set up rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: 'true'
      - name: Build
        run: cargo build --release

      - name: Package
        run: tar -czvf release-${{ steps.variables.outputs.ARCH }}.tar.gz -C target/release .

      - name: Publish Release
        id: publish_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            release-${{ steps.variables.outputs.ARCH }}.tar.gz
          tag_name: ${{ steps.variables.outputs.SHORT_SHA }}
          release_name: Release ${{ steps.variables.outputs.SHORT_SHA }}
          body: |
            Release for commit ${{ steps.variables.outputs.SHORT_SHA }}
